---
name: linting
on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2 
      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.3.0

